### ISSUE TITLE
Secrets.json missing

### ISSUE THREAD

**Issue by mhassanrahman** [AnaghSharma/Carol-Xamarin#10]
The code is not compiling as Secrets.json file is missing.

**Comment by AnaghSharma** [comment]
Hi @mhassanrahman , `Secrets.json` is the file which contains the API Key that you get after registering your app at Musixmatch. API Key is supposed to be private that's why `Secrets.json` is not a part of the repo, although it is required to run the app. Remember all the API calls use this secret API Key to fetch the lyrics.

* If you just want to install and use the app, [download the latest .pkg file from here](https://github.com/AnaghSharma/Carol/releases)
* If you want to explore the code and see how the app works, you will have to add a `Secrets.json` file at the root of your project in Visual Studio and also register an app at Musixmatch in order to get the API Key. For more information, check [CONTRIBUTING.md](https://github.com/AnaghSharma/Carol/blob/master/CONTRIBUTING.md)
