### ISSUE TITLE
Feature Requests 

### ISSUE THREAD

**Issue by jakeround** [AnaghSharma/Carol-Xamarin#12]
Hey Anagh,

I have a few feature requests for the application.

- Clicking the album artwork should open the music player window, so Spotify should be the top window when clicking the artwork.
- Lyric's should scroll as the song's playing.
- Dark/Light mode for macOS Mojave

Apart from that, loving your application keep up the work. 👍🏻👍🏻

### Your system configuration
macOS Mojave

**Comment by AnaghSharma** [comment]
Hi Jake,

Glad to know that you liked the app.

- Clicking the album artwork should open the music player window. Yes, this can be done but I am not sure it will be intuitive enough. I am showing artwork in a circular container which does not look like it is clickable. The cursor can be changed to pointing hand to show it is clickable.
- Lyrics cannot scroll as the song progresses because I do not have access to complete Musixmatch API. Complete API is paid and pretty expensive for me (A minimum of $1000 USD per month).
- The UI is already dark. In order to support Light mode, I will have to first design it. This feature can be implemented. I am just waiting for the public release of macOS Mojave.

Thanks,
Anagh

**Comment by AnaghSharma** [comment]
Added this in the latest redesign.
