### ISSUE TITLE
Application Crashes

### ISSUE THREAD

**Issue by jakeround** [AnaghSharma/Carol-Xamarin#9]
While creating an issue, please follow and clearly specify the following - 

### The unexpected behaviour

Application crashed under macOS Mojave 10.14
### Steps to reproduce

Launch Application
### Your system configuration

Macbook Pro 2015
macOS Mojave 10.14 Beta 1

**Comment by AnaghSharma** [comment]
Hi Jake,

Thanks for submitting the issue. I am already aware of it. In fact, in my case, Spotify also gets crashed at the same time. 
If no music is playing the app works fine, so I guess the problem is in the song detection.  Will try to figure out what can be the problem over the weekend.

Regards

**Comment by AnaghSharma** [comment]
@jakeround Just updated to Mojave 10.14 Beta 2 and its working now. There are some UI rendering issues though.

**Comment by jakeround** [comment]
Dope, installed and looks great. Nice work
